<a href="https://colab.research.google.com/github/sebasatarama/EB-2022-1-CC50/blob/main/Modelo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as ans
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [3]:
ds = pd.read_csv('DEvideos_cc50.csv')

#Para predecir Likes:
Predecir likes parece ser que es lo más sencillo, ya que se cuenta con una presición de más del 86%

In [14]:
X = ds[['views', 'dislikes', 'comment_count']]
y = ds['likes']

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=101)

In [16]:
lm = LinearRegression()

In [17]:
lm.fit(X_train, y_train)

LinearRegression()

In [19]:
coef_df = pd.DataFrame(lm.coef_,X.columns,columns=['Coeficiente'])

In [20]:
coef_df

Coeficiente
views             0.022630
dislikes         -1.323382
comment_count     3.497573

Presición del modelo

In [18]:
print(lm.score(X_test, y_test))

0.860788189775233


Algunas de las predicciones

In [21]:
predictions = lm.predict(X_test)

In [22]:
predictions

array([4001.90446986, 1818.33714353,  829.46468466, ..., 1166.87413559,
       1368.33503634,  449.58562162])

#Para predecir Dislikes
El modelo solo arroja una presisción del 56%, muy inferior a cuando se intentaban predecir los likes.

In [42]:
X = ds[['views', 'likes', 'comment_count']]
y = ds['dislikes']

In [43]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=101)

In [44]:
lm = LinearRegression()

In [45]:
lm.fit(X_train, y_train)

LinearRegression()

Presición del modelo

In [46]:
print(lm.score(X_test, y_test))

0.5623792703434035


Algunas predicciones. Se puede observar que el modelo arroja incluso valores negativos. Este puede ser un motivo de la baja presición.

In [30]:
predictions = lm.predict(X_test)

In [31]:
predictions

array([  70.76049362, -160.42651905, -221.28085246, ..., -216.50739359,
       -147.64030567, -272.65543181])

#Para predecir views
Observamos que es un modelo más preciso que el que se usa para predecir dislikes, pero menos preciso que el predice likes.

In [52]:
ÑX = ds[['dislikes', 'likes', 'comment_count']]
y = ds['views']

In [53]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=101)

In [54]:
lm = LinearRegression()

In [55]:
lm.fit(X_train, y_train)

LinearRegression()

Presición del modelo

In [56]:
print(lm.score(X_test, y_test))

0.7346622045361078


Algunas predicciones.

In [57]:
predictions = lm.predict(X_test)

In [58]:
predictions

array([232449.19653161, 201860.73890918, 185217.01195109, ...,
       194055.05408915, 181254.03862219, 182447.05509513])