<a href="https://colab.research.google.com/github/sebasatarama/EB-2022-1-CC50/blob/main/Modelo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as ans
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [ ]:
ds = pd.read_csv('DEvideos_cc50.csv')

#Para predecir Likes:
Predecir likes parece ser que es lo más sencillo, ya que se cuenta con una precisión de más del 86%

In [ ]:
X = ds[['views', 'dislikes', 'comment_count']]
y = ds['likes']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=101)

In [ ]:
lm = LinearRegression()

In [ ]:
lm.fit(X_train, y_train)

LinearRegression()

Precisión del modelo

In [ ]:
print(lm.score(X_test, y_test))

0.860788189775233


Algunas de las predicciones

In [ ]:
predictions = lm.predict(X_test)

In [ ]:
predictions

array([4001.90446986, 1818.33714353,  829.46468466, ..., 1166.87413559,
       1368.33503634,  449.58562162])

#Para predecir Dislikes
El modelo solo arroja una precisión del 56%, muy inferior a cuando se intentaban predecir los likes.

In [ ]:
X = ds[['views', 'likes', 'comment_count']]
y = ds['dislikes']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=101)

In [ ]:
lm = LinearRegression()

In [ ]:
lm.fit(X_train, y_train)

LinearRegression()

Precisión del modelo

In [ ]:
print(lm.score(X_test, y_test))

0.5623792703434035


Algunas predicciones. Se puede observar que el modelo arroja incluso valores negativos. Este puede ser un motivo de la baja precisión.

In [ ]:
predictions = lm.predict(X_test)

In [ ]:
predictions

array([  70.76049362, -160.42651905, -221.28085246, ..., -216.50739359,
       -147.64030567, -272.65543181])

#Para predecir views
Observamos que es un modelo más preciso que el que se usa para predecir dislikes, pero menos preciso que el predice likes.

In [ ]:
ÑX = ds[['dislikes', 'likes', 'comment_count']]
y = ds['views']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=101)

In [ ]:
lm = LinearRegression()

In [ ]:
lm.fit(X_train, y_train)

LinearRegression()

Precisión del modelo

In [ ]:
print(lm.score(X_test, y_test))

0.7346622045361078


Algunas predicciones.

In [ ]:
predictions = lm.predict(X_test)

In [ ]:
predictions

array([232449.19653161, 201860.73890918, 185217.01195109, ...,
       194055.05408915, 181254.03862219, 182447.05509513])